In [1]:
import pandas as pd
import matplotlib
print(pd.__version__, matplotlib.__version__)

3.0.5 3.11.1

In [15]:
df1 = pd.read_csv("/Users/arw/AudreyRWard.github.io/Lab2_data_notebook/4389908.csv")
df1.head()

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,PRCP,SNOW,SNWD
0,USC00129427,"WEST LAFAYETTE PURDU, IN US",40.41667,-86.91667,189.0,1950-01-01,0.04,0.0,0.0
1,USC00129427,"WEST LAFAYETTE PURDU, IN US",40.41667,-86.91667,189.0,1950-01-02,0.01,0.0,0.0
2,USC00129427,"WEST LAFAYETTE PURDU, IN US",40.41667,-86.91667,189.0,1950-01-03,0.64,0.0,0.0
3,USC00129427,"WEST LAFAYETTE PURDU, IN US",40.41667,-86.91667,189.0,1950-01-04,2.84,0.0,0.0
4,USC00129427,"WEST LAFAYETTE PURDU, IN US",40.41667,-86.91667,189.0,1950-01-05,0.29,0.0,0.0

In [16]:
df2 = pd.read_csv("/Users/arw/AudreyRWard.github.io/Lab2_data_notebook/4389909.csv")
df2.head()

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,PRCP,SNOW,SNWD
0,USC00129435,"W LAFAYETTE SEW PLANT, IN US",40.4169,-86.9058,161.8,1975-08-01,0.10,NaN,NaN
1,USC00129435,"W LAFAYETTE SEW PLANT, IN US",40.4169,-86.9058,161.8,1975-08-02,0.82,NaN,NaN
2,USC00129435,"W LAFAYETTE SEW PLANT, IN US",40.4169,-86.9058,161.8,1975-08-03,0.00,NaN,NaN
3,USC00129435,"W LAFAYETTE SEW PLANT, IN US",40.4169,-86.9058,161.8,1975-08-04,0.00,NaN,NaN
4,USC00129435,"W LAFAYETTE SEW PLANT, IN US",40.4169,-86.9058,161.8,1975-08-05,0.65,NaN,NaN

In [17]:
df3 = pd.read_csv("/Users/arw/AudreyRWard.github.io/Lab2_data_notebook/4389911.csv")
df3.head()

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,PRCP,SNOW,SNWD
0,USC00129435,"W LAFAYETTE SEW PLANT, IN US",40.4169,-86.9058,161.8,2011-01-01,0.54,NaN,NaN
1,USC00129435,"W LAFAYETTE SEW PLANT, IN US",40.4169,-86.9058,161.8,2011-01-02,0.00,NaN,NaN
2,USC00129435,"W LAFAYETTE SEW PLANT, IN US",40.4169,-86.9058,161.8,2011-01-03,0.00,NaN,NaN
3,USC00129435,"W LAFAYETTE SEW PLANT, IN US",40.4169,-86.9058,161.8,2011-01-04,0.00,NaN,NaN
4,USC00129435,"W LAFAYETTE SEW PLANT, IN US",40.4169,-86.9058,161.8,2011-01-05,0.00,NaN,NaN

In [18]:
df4 = pd.read_csv("/Users/arw/AudreyRWard.github.io/Lab2_data_notebook/4389913.csv")
df4.head()

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,PRCP,SNOW,SNWD
0,US1INTP0092,"LAFAYETTE 1.1 WSW, IN US",40.4069,-86.8903,213.7,2023-05-20,0.0,0.0,NaN
1,US1INTP0092,"LAFAYETTE 1.1 WSW, IN US",40.4069,-86.8903,213.7,2023-05-21,0.0,0.0,NaN
2,US1INTP0092,"LAFAYETTE 1.1 WSW, IN US",40.4069,-86.8903,213.7,2023-05-22,0.0,0.0,NaN
3,US1INTP0092,"LAFAYETTE 1.1 WSW, IN US",40.4069,-86.8903,213.7,2023-05-23,0.0,0.0,NaN
4,US1INTP0092,"LAFAYETTE 1.1 WSW, IN US",40.4069,-86.8903,213.7,2023-05-24,0.0,0.0,NaN

In [21]:
merged_df = pd.concat([df1, df2, df3, df4], ignore_index=True)

In [22]:
merged_df.head()

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,PRCP,SNOW,SNWD
0,USC00129427,"WEST LAFAYETTE PURDU, IN US",40.41667,-86.91667,189.0,1950-01-01,0.04,0.0,0.0
1,USC00129427,"WEST LAFAYETTE PURDU, IN US",40.41667,-86.91667,189.0,1950-01-02,0.01,0.0,0.0
2,USC00129427,"WEST LAFAYETTE PURDU, IN US",40.41667,-86.91667,189.0,1950-01-03,0.64,0.0,0.0
3,USC00129427,"WEST LAFAYETTE PURDU, IN US",40.41667,-86.91667,189.0,1950-01-04,2.84,0.0,0.0
4,USC00129427,"WEST LAFAYETTE PURDU, IN US",40.41667,-86.91667,189.0,1950-01-05,0.29,0.0,0.0

In [23]:
print(merged_df['DATE'].min())
print(merged_df['DATE'].max())

1950-01-01
2026-09-07

In [29]:
merged_df = merged_df.sort_values(by=["DATE", "STATION"]).reset_index(drop=True)

In [32]:
merged_df.head()

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,PRCP,SNOW,SNWD
0,USC00129427,"WEST LAFAYETTE PURDU, IN US",40.41667,-86.91667,189.0,1950-01-01,0.04,0.0,0.0
1,USC00129430,"WEST LAFAYETTE 6 NW, IN US",40.47500,-86.99190,215.8,1950-01-01,0.05,NaN,NaN
2,USW00014835,"LAFAYETTE PURDUE UNIVERSITY AIRPORT, IN US",40.41236,-86.94739,181.7,1950-01-01,0.07,0.0,0.0
3,USC00129427,"WEST LAFAYETTE PURDU, IN US",40.41667,-86.91667,189.0,1950-01-02,0.01,0.0,0.0
4,USC00129430,"WEST LAFAYETTE 6 NW, IN US",40.47500,-86.99190,215.8,1950-01-02,0.55,NaN,NaN